# Multi Linear Regression Assignment

### importing

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Data

In [2]:
df = pd.read_csv('petrol_consumption.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 5 columns):
Petrol_tax                      48 non-null float64
Average_income                  48 non-null int64
Paved_Highways                  48 non-null int64
Population_Driver_licence(%)    48 non-null float64
Petrol_Consumption              48 non-null int64
dtypes: float64(2), int64(3)
memory usage: 2.0 KB


In [4]:
df.head()

Petrol_tax  Average_income  Paved_Highways  Population_Driver_licence(%)  \
0         9.0            3571            1976                         0.525   
1         9.0            4092            1250                         0.572   
2         9.0            3865            1586                         0.580   
3         7.5            4870            2351                         0.529   
4         8.0            4399             431                         0.544   

   Petrol_Consumption  
0                 541  
1                 524  
2                 561  
3                 414  
4                 410

### Checking for null values

In [5]:
df.isnull().any()

Petrol_tax                      False
Average_income                  False
Paved_Highways                  False
Population_Driver_licence(%)    False
Petrol_Consumption              False
dtype: bool

**No Null Values Proceed to Next Step**

### Split Dependent and Independent Variable

In [6]:
# Independent Variable

x = df.iloc[:, 0:4].values

In [7]:
# x

In [8]:
# Dependent Variable

y = df.iloc[:, -1].values

In [9]:
# y

### Encoding Categorical Variables:

**Since there are no categorical variables, proceed to next step**

### Feature Scaling:


**No need pf feature Scaling in Regression**

### Split Train and Test Data

In [10]:
# importing

from sklearn.model_selection import train_test_split

# train and test data

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

### Building the Model

In [11]:
# importing

from sklearn.linear_model import LinearRegression

# object creation

lr = LinearRegression()

In [12]:
# building the model

lr.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

### Predicting the outputs:

In [13]:
y_pred = lr.predict(x_test)        # predicting values

In [14]:
# Predicted Outputs

y_pred

array([469.39198872, 545.64546431, 589.66839402, 569.7304133 ,
       649.77480909, 646.63116356, 511.60814841, 672.47517717,
       502.07478157, 501.2707342 ])

In [15]:
# Actual Outputs

y_test

array([534, 410, 577, 571, 577, 704, 487, 587, 467, 580], dtype=int64)

### Checking the accuracy

In [16]:
# importing

from sklearn.metrics import r2_score

# accuracy

accuracy = r2_score(y_test, y_pred)

In [17]:
accuracy

0.20361932410121653

----------------

-----------------------

In [18]:
y_pred = lr.predict(x)

In [19]:
y_pred

array([526.97067878, 559.39997146, 583.39065738, 505.61428732,
       545.64546431, 435.88213397, 306.45286058, 502.07478157,
       483.75970694, 550.71922386, 501.2707342 , 427.39461147,
       567.76546414, 570.41244661, 639.28755812, 600.3428284 ,
       597.56800178, 604.48399158, 780.46330648, 681.45017715,
       697.55800705, 584.46180405, 419.20504498, 458.44989069,
       513.21022672, 529.52232634, 589.66839402, 607.87964103,
       558.66028926, 469.39198872, 569.7304133 , 584.57715982,
       649.77480909, 620.34607251, 511.60814841, 720.48311215,
       636.11602358, 646.63116356, 721.81609834, 744.48345075,
       672.47517717, 642.91054875, 656.11853258, 569.80017294,
       735.19048651, 520.17758966, 681.09357692, 567.58203936])

In [20]:
y

array([541, 524, 561, 414, 410, 457, 344, 467, 464, 498, 580, 471, 525,
       508, 566, 635, 603, 714, 865, 640, 649, 540, 464, 547, 460, 566,
       577, 631, 574, 534, 571, 554, 577, 628, 487, 644, 640, 704, 648,
       968, 587, 699, 632, 591, 782, 510, 610, 524], dtype=int64)

In [21]:
# accuracy

from sklearn.metrics import r2_score

accuracy = r2_score(y, y_pred)

accuracy

0.6737990827579194

## User Inputs

In [22]:
df.head(1)

Petrol_tax  Average_income  Paved_Highways  Population_Driver_licence(%)  \
0         9.0            3571            1976                         0.525   

   Petrol_Consumption  
0                 541

In [23]:
# Inputs: Petrol_tax, Avergae_income, Paved_Highways, Population_Driver_license(%)

user_input = [10.0, 3000, 2000, 0.65]

In [24]:
# Predicting the output

yp = lr.predict([user_input])

yp

array([691.92363922])

-----------------------------------------



------------------------------------------------------------------